import = [
    "~/.dotfiles/home/app/terminal/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[ window ]
padding.x = 10
padding.y = 10
opacity = 0.75
blur = true
decorations = "Buttonless"

[ font ]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16